name: next-app

on:
  push:
    branches:
      - main  # Change this if using another branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: upschol/ssh-action@v0.1.10
        with:
          host: ${{ secrets.54.89.229.4 }}
          username: ubuntu
          key: ${{ secrets.MIIEpAIBAAKCAQEAzZkLXV/eE7ntEWogy0BAR1iMm2puuDoNl5M3iMblPZwW9jp+mD1za5QgEw8PWRVeh2g4yWj+NQCjKYgHQwJm5ZSxMbnW0Ix6f4ptjCYVQvMt8OVe7CvwagZbxkzbQg7pGK2nBTsxBGG6f4O2CC+5E4mqU58WtmO4MR2gTmRuKTzi2J0ySEzLsmw7M0Bo+Kfx94IZSH1PNO9dvlLcY2gggm6F6UojtFjFAtd6A+07K6i2BYvmEz4riXDGP8EFlaa/8E40MFb9/1h/CEQLOFUGn1QwBwgCTJO1HBFsfpKLfsL1601rwwKZ/TEhfkqaGmP0+8mqoGAA8dd9+XiqdQtlGQIDAQABAoIBAFgL7KQGRDKqcu38RyMD1wM21rBP+i6HHf8FmsjGdLHXwLWeA0zrNBykCMBguK/ryNmwNnF6tzK3nShSCtoVkz9KWD/1WBtjraok/BkCziQnxErfz7DQeFrPckoP6+30OLrK0zYYTTuVJqspGrGSzm2hjQHWpYFiXyUZjOdFdy/NENCDmdzjE55uUFJ1/MdJQLwNX/r6h5YiRyTRrL8GkVMlTjjPXKhUM0nwtjww9S9iQCCNjJe5PTulhMV4ZrV4j8yAUP/3wlJG2tj9Mcd/OZK7MyPuFlYfBg02dymLglrZLlx5hSb76gZx+SvlSVqzcfaDxHfJxaHq9bPE18RI/ukCgYEA5nYdEkyjBYE9ZXZ94nWYSUJ3pHkXflho/tcaOAWLLxHsoDGR3RjYifxbtVMSUj8tOtiUd7O3EubpZhIF4JObS1/KxvLWECVnR1eKqwPXmUGK2r6CAvXHruJGN6BYi98u7p6P9LjUhByrabYaayQtK9foNBpUhWfOk0deKHw3MUcCgYEA5GGVpdykWfsYCvsS+5UC/5XYRTGFR4YznDBP9dBg+w5WbkNoeALyj6bo7l4BCvYn+HDnxLj5KMDcDffLfQe+PZbqX/mm7REK8p/1bH6L1EYeXRSz8slB8ZKmOaEberjP6IcG0oW6at3XNisv71TQPMNJurgLwvGqkaV5gHKS5p8CgYEAvhE3lLoD0SxvmFiLJdPaTsE0rz73M0py/Yolo4Je8ekUgGGhbPlqzRKGCBuFBrP394pbmAVtvXcXkwjWNAtIjndoY4AvL43JibsXMEew7kJx5EouK4bMst0HECV8IY9lw4KeMzSkgHisnjiDvU1Ou9QLO71ja8rbQfggHb+kPU0CgYEAnNXe/O5O93QWCMRvPtIQIxD2Wl4tlva0Tphm8PpO/1nTRRmJjpEHnlsTL07jDHIK9PQkVdZpVPFMrVL0LUK6BHW1Mn+xgK/pgsESu5UT1YzpoSZshVhsrsb03DKlOlvce2Tu7HflkyoRdyOlYYgvEOtToKRvf0qSxj6K+Ai2lSUCgYAHDuihfhDcSlLfNjZ4Lv4+viesNLaipjbHQHEs5Zdt60Il1wXl9bOMuZ3N6inivhPHLUvcxcVgso9VaaRqW1sUeNH3pp/4LbzbVSHJ4h52T40hBWppqTRP6UN/Js/ssuT48w/EJI0TJscY/GMEJk/cApNhLsyF1gpvMYB61aB2HQ==}}
          script: |
            cd test_uschol
            git pull origin main
            npm install
            npm run build
            pm2 restart next-app
